---
abstract: 'Generates iCalendar (RFC 2445) calendar files'
author:
  - 'Jesse Vincent <jesse@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::LongString: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-ICal
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Accessor: 0
  Class::ReturnValue: 0
  MIME::QuotedPrint: 0
  Text::vFile::asData: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.16
