name: Data-ICal
version: 0.001
abstract: [One line description of module's purpose here]
author: Jesse Vincent <jesse@bestpractical.com>
license: perl
distribution_type: module
requires:
  Test::More: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
