abstract: Generates iCalendar (RFC 2445) calendar files
author: Jesse Vincent <jesse@bestpractical.com>
build_requires: 
  Test::LongString: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Data-ICal
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0
  Class::ReturnValue: 0
  MIME::QuotedPrint: 0
  Text::vFile::asData: 0
version: 0.09
